// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "enrollments",
    id: "b53e511d-f0a1-4459-a3f6-4bc0bad4ad19",
    method: "POST",
    address: "http://34.87.20.129/v1/graphql",
    data:
      '{"query":"query($email:String! $includeTasks:Boolean!){\\n  enrollments(userEmail:$email includeTasks:$includeTasks){\\n    id\\n    slug\\n    title\\n    description\\n    tasks{\\n      id\\n      slug\\n      type\\n      title\\n      description\\n      parentTaskSlug\\n      completionRate\\n    }\\n    completionRate\\n  }\\n}","variables":"{\\n    \\"email\\":\\"shivateja.dasi@the10xacademy.com\\",\\n    \\"includeTasks\\":true\\n}"}',
    headers: {
      "Accept-Language": "en-US,en;q=0.9",
      Authorization:
        "Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNoaXZhdGVqYS5kYXNpQHRoZTEweGFjYWRlbXkuY29tIiwidXNlciI6eyJ1dWlkIjoiNTEzYmIxNTktZjlkZS01M2YxLWJkZmItYTlkMzM0NDM0MzdmIiwiZmlyc3ROYW1lIjoiU2hpdmF0ZWphIiwibGFzdE5hbWUiOiJEYXNpIiwiZW1haWwiOiJzaGl2YXRlamEuZGFzaUB0aGUxMHhhY2FkZW15LmNvbSIsInBob25lTnVtYmVyIjpudWxsLCJpc1Bob25lTnVtYmVyVmVyaWZpZWQiOm51bGwsIm5pY2tOYW1lIjoiU2hpdmF0ZWphIERhc2kiLCJyb2xlIjoiQURNSU4iLCJhZGRyZXNzIjoiIiwiY2l0eSI6IiIsImF2YXRhcl91cmwiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQVRYQUp3X1dLdTdEOVd6Y1ZyWk9TT3diTEVBX0IyS2w1WFBsT1NidTFwNz1zOTYtYyIsImNyZWF0ZWRBdCI6MTYzODgxMTAwNywidXBkYXRlZEF0IjoxNjM5ODEwNzA4LCJsaW5rZWRJblVSTCI6bnVsbH0sImV4cCI6MTY2NDYyNzc4OCwianRpIjoiMTA0NDg3MDA4ODE0Mzk1NzMzNTAwIiwiaWF0IjoxNjYzNzYzNzg4LCJpc3MiOiJnb29nbGUiLCJuYmYiOjE2NjM3NjM3ODh9.FYAANrQEFU6MKvun_fT2BhnL0vgFfiXU80p9Q-zTpuYx3UHD63jgv7UJ40OfTCYv5ncgLBpDxNW0lOQSfl3GyA",
      Connection: "keep-alive",
      Origin: "http://34.87.20.129",
      Referer: "http://34.87.20.129/",
      "User-Agent":
        "Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Mobile Safari/537.36",
      accept: "application/json, multipart/mixed",
      "content-type": "application/json"
    },
    post(response) {
      pm.test("Status code is 200", function() {
        pm.response.to.have.status(200);
      });
    }
  });
}
